package de.awi.floenavigation;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteException;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import android.widget.ArrayAdapter;

public class DatabaseHelper extends SQLiteOpenHelper {

    private static final String DB_NAME = "FloeNavigation";
    private static final int DB_VERSION = 1;
    private static final String TAG = "DatabaseHelpler";

    private static DatabaseHelper dbInstance;

    public static final int firstStationIndex = 0;
    public static final int secondStationIndex = 1;
    public static final int INITIALIZATION_SIZE = 2;
    public static final int NUM_OF_BASE_STATIONS = 2;
    public static final int NUM_OF_DEVICES = 1234;

    //Database Tables Names
    public static final String fixedStationTable = "AIS_FIXED_STATION_POSITION";
    public static final String stationListTable = "AIS_STATION_LIST";
    public static final String mobileStationTable = "AIS_MOBILE_STATION_POSITION";
    public static final String usersTable = "USERS";
    public static final String sampleMeasurementTable = "SAMPLE_MEASUREMENT";
    public static final String deviceListTable = "DEVICE_LIST";
    public static final String waypointsTable = "WAYPOINTS";
    public static final String baseStationTable = "BASE_STATIONS";
    public static final String betaTable = "BETA";
    public static final String staticStationListTable = "STATION_LIST";


    //Database Fields Names
    public static final String stationName = "AIS_STATION_NAME";
    public static final String latitude = "LATITUDE";
    public static final String longitude = "LONGITUDE";
    public static final String recvdLatitude = "RECEIVED_LATITUDE";
    public static final String recvdLongitude = "RECEIVED_LONGITUDE";
    public static final String xPosition = "X_POSITION";
    public static final String yPosition = "Y_POSITION";
    public static final String sog = "SPEED_OVER_GROUND";
    public static final String cog = "COURSE_OVER_GROUND";
    public static final String alpha = "ALPHA";
    public static final String beta = "BETA";
    public static final String packetType = "LAST_RECEIVED_PACKET_TYPE";
    public static final String predictionAccuracy = "PREDICTION_ACCURACY";
    public static final String mmsi = "MMSI";
    public static final String staticStationName = "STATION_NAME";
    public static final String stationType = "STATION_TYPE";
    public static final String distance = "DISTANCE";
    public static final String deviceType = "DEVICE_TYPE";
    public static final String updateTime = "UPDTAE_TIME";
    public static final String isPredicted = "IS_POSITION_PREDICTED";
    public static final String isLocationReceived = "IS_LOCATION_RECEIVED";
    public static final String userName = "USERNAME";
    public static final String password = "PASSWORD";
    public static final String deviceName = "DEVICE_NAME";
    public static final String deviceShortName = "DEVICE_SHORT_NAME";
    public static final String label = "LABEL";

    //Initial Position of Setup Points in Custom Coordinate System
    public static final long station1InitialX = 0;
    public static final long station1InitialY = 0;
    public static final long station2InitialX = 500;
    public static final long station2InitialY = 0;

    public static final String[] stationTypes = {
            "Tent",
            "Hut",
            "Mast",
            "Fixpoint",
            "Polarstern",
            "Pistenbully",
            "Hovercraft",
            "Scooter",
            "Pulka",
            "Buoy"
    };

    public static final String[] deviceNames = {

            "2 m Blake Trawl",
            "3D camera",
            "8-Channel Temperature Lance",
            "Absorption and beam attenuation",
            "Accoustic Geodetic Seafloor Station",
            "Achnor dredge",
            "Acoustic Doppler Current Profiler",
            "Acoustic Doppler Current Profiler, vessel-mounted",
            "Acoustic module",
            "Acoustic releaser",
            "Active Sampling and Measuring System",
            "Advanced hydraulic piston corer",
            "Advanced spectral irradiance meter",
            "Aeolian dust sample",
            "Aerial photography",
            "Aerial sample, bulk filtered",
            "Aerial sample, pump",
            "Aerological investigations",
            "Aerosol sample",
            "Agassiz Trawl",
            "AGP-floater",
            "Air chemistry observatory",
            "Airborne electromagnetic induction sounding",
            "Airborne radio-echo sounding",
            "Aircraft",
            "Aktiv positioniertes Explorationsgerät",
            "ALBEX lander",
            "Algae frame",
            "All plastic clean surface pumped supply",
            "Anaerobic box - ROV",
            "Apageo corer",
            "Apex floater",
            "Apstein net",
            "Aquamonitor",
            "Aquatracka",
            "Argo float",
            "Argos buoy",
            "Argos sea ice buoy",
            "Arobics",
            "Auger",
            "Auto-Recording Instrumented Sampler",
            "Autoclave corer",
            "Autoclave piston corer",
            "Automatic depth gauges",
            "Automatic stage sensor station",
            "Automatic weather station",
            "Autonome colonisation module",
            "Autonome pluridisciplinary module",
            "Autonomous langrangian circulation explorer",
            "Autonomous scanning modul",
            "Autonomous underwater vehicle",
            "Autonomous underwater vehicle/multibeam",
            "Axe",
            "Baited free-fall benthic amphipod trap",
            "Balloon-borne Sonde",
            "Banyuls Benthic Lander/Multicorer",
            "Barbless Hook",
            "Barometer",
            "Bathysnack - baited bathysnap",
            "Bathysnap - free-fall time-lapse camera system",
            "Bathysonde",
            "Batomat",
            "Baumkurre",
            "Beach seine",
            "Beam trawl",
            "Beamtrawl commercial with bobbin, width 3.5 m, meshsize 1 cm",
            "Beamtrawl commercial with bobbin, width 8 m, meshsize 1 cm",
            "Beamtrawl of RV Senkenberg with forerun chain, width 2 m, meshsize 1 cm",
            "Beamtrawl of RV Senkenberg with forerun chain, width 4 m, meshsize 1 cm",
            "Beamtrawl of RV Senkenberg with forerun chain, width 4 m, meshsize 4 cm",
            "Beamtrawl of RV Senkenberg without forerun chain, width 2 m, meshsize 0.4 cm",
            "Beamtrawl of RV Senkenberg without forerun chain, width 2 m, meshsize 1 cm",
            "Beamtrawl of RV Senkenberg without forerun chain, width 4 m, meshsize 1 cm",
            "Beamtrawl of Shrimpcutter POLARIS (Neuharlinger Siel) with bobbin, width 7.5 m,",
            "Beamtrawl with bobbin, width 3 m, meshsize 1 cm",
            "Beamtrawl with forerun chain, width 3 m, meshsize 1 cm",
            "Beamtrawl without forerun chain, width 3 m, meshsize 1 cm",
            "Benthic Chamber",
            "Benthic chamber lander",
            "Benthic Crawler",
            "Benthic Experimental Chamber Instrument",
            "Benthic flux chamber",
            "Benthic flux chamber, submersible depl",
            "Benthic flux meter",
            "Benthic Mesocosm Experiment",
            "Benthic Oxygen Lander System",
            "Benthic-Boundary-Layer Profiler",
            "Bentho-pelagic trawl",
            "Beton-Dropper",
            "Beyer sledge",
            "Bibo",
            "Bics",
            "Bio-Optical Profiler",
            "Bio-Rosette",
            "Biodiversity mapping",
            "Biogenic Reef Ichthyofauna Lander",
            "Biogeochemical observatory",
            "Biological sample",
            "Biology",
            "BIOMAPER",
            "Biomoc net",
            "Blade core",
            "Bobber float",
            "Bobcorer",
            "Bongo net",
            "Boomer",
            "Boomerang-Grab",
            "Boomerang-Lot",
            "Borer",
            "Botanical mapping",
            "Bottle (borosilicate glass, 500ml)",
            "Bottle, Kemmerer",
            "Bottle, multi level trace metal",
            "Bottle, Nalgene",
            "Bottle, Nalgene 10-L",
            "Bottle, Nalgene 4-L",
            "Bottle, Nalgene 5-L",
            "Bottle, Nansen",
            "Bottle, Niskin",
            "Bottle, Niskin 1.6-L",
            "Bottle, Niskin 10-L",
            "Bottle, Niskin 12-L",
            "Bottle, Niskin 2-L",
            "Bottle, Niskin 20-L",
            "Bottle, Niskin 25-L",
            "Bottle, Niskin 3-L",
            "Bottle, Niskin 30-L",
            "Bottle, Niskin 5-L",
            "Bottle, Niskin 8-L",
            "Bottle, Ruttner",
            "Bottle, unknown",
            "Bottle, unknown 10-L",
            "Bottle, unknown 2-L",
            "Bottle, unknown 20-L",
            "Bottle, unknown 4-L",
            "Bottle, unknown 5-L",
            "Bottle, Van Dorn",
            "Bottle, Van Dorn 2.2-L",
            "Bottom Acoustic Doppler Current Profiler",
            "Bottom Boundary Lander",
            "Bottom grab (Petterson)",
            "Bottom grab (Smith-McIntyre)",
            "Bottom lander",
            "Bottom lander, chamber",
            "Bottom lander, lance",
            "Bottom lander, profile",
            "Bottom net",
            "Bottom pressure recorder",
            "Bottom trawl",
            "Bottom water sampler",
            "Bottom water station",
            "Bottom water temperature mooring",
            "Bottom-towed CSEM",
            "Box corer",
            "Box corer (Haja)",
            "Box corer (modified Reineck, 0.02 m**2)",
            "Box corer (Reineck)",
            "Box corer with microelectrode",
            "Boxes (5x5x20 cm)",
            "Broadband Ocean Bottom Seismometer",
            "Bubble catcher",
            "Bubble catcher, large",
            "Bubble catcher, small",
            "Bubble meter",
            "Bubble monitoring box",
            "Bucket water sampling",
            "Bucket, plastic",
            "Bucky ball",
            "Buma net",
            "Baseline Surface Radiation Network",
            "Buoy",
            "Butterfly net",
            "Butterfly sampler",
            "Byelorussian sampler",
            "Cage",
            "Calcofi",
            "Calculation",
            "Calibration",
            "CALMAR benthic chamber",
            "Caltech Active Strand Cloudwater Collector",
            "Calypso Corer",
            "Calypso Corer II",
            "Calypso Corer III",
            "Calypso Square Core System",
            "Calypso square corer",
            "Camera",
            "Camera sled",
            "Camera sledge system (Hopper)",
            "Camp",
            "Campod",
            "Carbonate",
            "CAT meter",
            "CATAMARAN",
            "Catamaran MESSIN",
            "Census in village",
            "Centrifuge",
            "Chain saw",
            "Chalut à perche (6 m beam trawl)",
            "Chamber corer",
            "Chemistry",
            "Chirp Sonar",
            "CHRIS-on-PROBA",
            "Clam dredge",
            "Claw sample",
            "Clay pit",
            "Climate monitoring station",
            "Closing net",
            "Closing trawl",
            "CO2 Sensor",
            "Coastal section",
            "Cobra percussion corer",
            "Collector Box",
            "Colonisateurs FG",
            "Colonization Trap",
            "Colonizer (Gent University)",
            "Colonizer-Marcrofauna",
            "Colonizer-Microbes",
            "Composite Core",
            "Cone penetration testing-lance",
            "Cone penetration testing-lance GOST",
            "Continuous centrifuging of non-toxic supply",
            "Controlled Source Electro-Magnetics",
            "Copepode net",
            "Core",
            "Core drilling",
            "Core wireline system",
            "Corer, submersible",
            "Course tow net",
            "Coûteaux corer",
            "Craelius corer",
            "CTD from ice float",
            "CTD Large",
            "CTD with gravity corer",
            "CTD-Acoustic Doppler Current Profiler",
            "CTD-Fluorometer",
            "CTD-Rapid Cast",
            "CTD-Scanfish",
            "CTD, FSI",
            "CTD, handheld",
            "CTD, memory",
            "CTD, profiling",
            "CTD, Seabird",
            "CTD, Seacat",
            "CTD, underway",
            "CTD/Rosette",
            "CTD/Rosette, ultra clean",
            "Current meter",
            "Current meter mooring",
            "Current meter, Aanderaa",
            "Current meter, vector measuring",
            "Current meter, vector-averaging",
            "Current meter, XCP",
            "Dachnowski corer",
            "Danisch Tripod",
            "Dart corer",
            "Data Transmission Node",
            "Day Grab",
            "Deep Flow",
            "Deep Lake Drilling System",
            "Deep Ocean Bottom Station",
            "Deep Ocean Profiler",
            "Deep Ocean Stealth Observation Lander",
            "Deep sea observatory",
            "Deep tow",
            "Deep Towed Active Source Instrument",
            "Deep towed SideScan Sonar",
            "Deep water sampler",
            "Deep-sea elevator ",
            "Deep-Sea Multibeam Echosounder",
            "Demersal fish trawl",
            "Dendro drill",
            "Dendrochronological drill by Preßler",
            "Dialyzer",
            "Difference-Pressure probe",
            "Digby dredge",
            "Digerfeldt-Letteval corer",
            "Digging pit",
            "Dinghi",
            "Dinoflagellate net - Galway pattern",
            "Diver-held corer",
            "Dolphin",
            "DOMEST surface boje",
            "Doppler radar, frequency modulated continuous wave",
            "Dopy",
            "Double MOCNESS 333",
            "Double opening/closing plankton net",
            "Double-MOCNESS, 1 sqm mouth opening",
            "Double-wall coring pipe",
            "Dredge",
            "Dredge, benthos",
            "Dredge, box",
            "Dredge, bucket",
            "Dredge, chain bag",
            "Dredge, frame",
            "Dredge, Igel",
            "Dredge, pipe",
            "Dredge, Rauschert",
            "Dredge, rock",
            "Dredge, triangle",
            "Drift net",
            "Driftcam",
            "Drifter",
            "Drifter, daily",
            "Drifter, longterm",
            "Drill, hydraulic",
            "Drilling/drill rig",
            "Driting rig with Parflux sediment traps",
            "Dropsonde",
            "Dummy",
            "Dust collector",
            "Dutch Piezo Cone",
            "Dynamic autoclave piston corer",
            "Echosounder",
            "Echosounder, sediment 3.5 kHz",
            "Eco191",
            "Ecological Observatory Module",
            "Eddy Covariance Station",
            "Eddy covariance system",
            "Eddy mooring",
            "Edelman auger",
            "Edelman corer",
            "Egersund trawl",
            "Eijkelkamp Kammerbohrer",
            "Ekman grab",
            "ELAC multibeam system",
            "Electro-magnetic Bird (EM-Bird)",
            "Electromagnetic induction/laser",
            "Electromechanical drill",
            "Electromechanical drill, dry hole",
            "Electromechanical drill, fluid-filled hole",
            "Electroplished stainless steel corer, Lichtert Industrie",
            "ELINOR Lander",
            "EM Profiler, NERIDIS II",
            "EM1002 multibeam echosounder",
            "EM302 multibeam echosounder",
            "EM710 multibeam echosounder",
            "Environmental investigation",
            "Epibenthic sledge",
            "EPICA drill",
            "Equilibrator",
            "Equilibrator, percolator",
            "Equilibrator, thin film",
            "Excavation",
            "Expendable bathythermograph",
            "Expendable CTD",
            "Expendable Sound Velocimeter",
            "Experiment",
            "Experimental piston corer",
            "Experimental tank (1 cubic metre) under artificial conditions",
            "Experimental tank (4 cubic metre) under artificial conditions",
            "Exploring system",
            "Exposure",
            "Extended core barrel",
            "Extensometer",
            "Fall-Lot Meischner KL",
            "Fast tracker for primary production",
            "Feeding Experiment",
            "FerryBox",
            "Fertilization experiment",
            "Firn auger",
            "Fish Bait",
            "Fish container",
            "Fish finder echolot, 20 kHz",
            "Fish finder echolot, EK60",
            "Fish undulating, recording system tow",
            "Fish-larvae net",
            "Fishing pole",
            "Fishing rod",
            "Flow injection analysis system",
            "Flügel- and Stechkammerbohrer",
            "Fluid Flow Observatory, Lander",
            "Fluid flux observatory",
            "Fluoreszenssonde",
            "Fluorometer",
            "Fluorometer, fast repetition rate",
            "Fluroprobe",
            "Flygt pump",
            "Foot pump",
            "Frahm corer",
            "Fransz net",
            "Free fall corer",
            "Free fall grab",
            "Free fall profile sonde",
            "Free fall pump CTD",
            "Free vehicle grab respirometer",
            "Free vehicle incubator",
            "Free vehicle respirometer",
            "Free vehicle trap chain",
            "Free vehicle water sampler",
            "Free-fall observation system",
            "Freeze corer",
            "Frequency test",
            "FTIR/atmospheric composition observation & Weather station/meteorological observation (WST)",
            "Fusil portugais",
            "Gas bubble sampler",
            "Gas catcher",
            "Gas hydrate experiment",
            "Gas Quantification, Lander",
            "Gas sampling device",
            "Gas sampling pentrometer tool",
            "Gas-tight sampling bottles mounted to ROV",
            "GasQuant",
            "Gauge sampler",
            "Gauge station",
            "GEMAX",
            "Gemini Niemistoe Corer",
            "Geo-ElectroMagnetic Shark (GEM Shark)",
            "Geodesy station",
            "Geoelectric",
            "Geological coring tube",
            "Geological mapping",
            "Geological profile sampling",
            "Geological sample",
            "Geomagnetic observatory",
            "Geomagnetics",
            "Geonor corer",
            "Geophysics",
            "Geothermic corer",
            "Geothermics",
            "Gerard bottle",
            "GES 10",
            "Giant box corer",
            "Giant box grab",
            "Giant gravity corer",
            "Giant gravity corer AWI",
            "Giant piston corer",
            "Giant piston corer (Calypso)",
            "Giant water sampler",
            "Gillnet",
            "Glas sphere water sampler",
            "Glider",
            "Global Acoustic Positioning System",
            "GNSS Receiver",
            "Go-Flo bottle 10L",
            "Go-Flo bottle 30L",
            "Go-Flo bottles",
            "Göteborg lander",
            "Göteborg maxilander",
            "Göteborg minilander",
            "Gothenberg inst for sampling more of the Ocean",
            "GOtland Deep Environmental Sampling Station",
            "Gouge auger (5 cm)",
            "Gouge auger, Pürckhauer",
            "Grab",
            "Grab (Shipek)",
            "Grab_BGR Video A",
            "Grab_BGR Video C",
            "Grab_BGR Video D",
            "Grande Ouverture Verticale 36/47",
            "Grande Ouverture Verticale trawl",
            "Granton trawl",
            "Gravimetry",
            "Gravity corer",
            "Gravity corer (Kiel type)",
            "Gravity corer (POI)",
            "Gravity corer (Russian type)",
            "Gravity corer GEOMAR",
            "Gravity Corer Pore Pressure",
            "Gravity corer Potsdam",
            "Gravity corer, hammer modified",
            "Gravity corer, UWITEC",
            "Gravity Corer/Heat Flow Probe",
            "Gravity Corer/temperature probe",
            "Ground-penetrating radar",
            "Gulf III plankton sampler",
            "Gulf plankton sampler (Nackthai)",
            "Hadal lander",
            "Hammer",
            "Hand (plastic-shovel)",
            "Hand auger (drill)",
            "Hand borer",
            "Hand borer (Szapa)",
            "Hand corer",
            "Hand corer (Instorf)",
            "Hand drill",
            "Hand ice drill",
            "Hand net",
            "Hand pipe corer",
            "Hand pump",
            "Hand push corer",
            "Hand trowel",
            "Hand water sampler",
            "HAPS corer",
            "Harpoon sampler",
            "Heat-Flow probe",
            "Heat-Flow probe, hard ground",
            "Heavy metal water sampler",
            "Helgoländer Larvennetz",
            "Helicopter",
            "Hensen net",
            "High Frequency Radar",
            "Hiller borer",
            "Hiller corer",
            "Hiller peat auge",
            "Hiller sampler",
            "Historical object",
            "HON-Kajak sediment corer",
            "Horizontal water sampler",
            "Howaldt-Bathysonde",
            "Hunting net",
            "Hydrate detection and stability determination",
            "Hydraulic Benthic Interactive Sampler",
            "Hydraulic piston corer",
            "Hydro corer",
            "Hydro optics",
            "Hydroacoustic surveys",
            "Hydrographic station",
            "Hydrometeorological station",
            "Hydrophon",
            "Hydrophysical profiler OLT-D",
            "HydroSweep",
            "HydroSweep/ParaSound Profile",
            "Hyperspectral Imager",
            "ICBM-Drifter",
            "Ice drill",
            "Ice measurement",
            "Ice station",
            "Ice survey",
            "Iceberg",
            "Ichthyo plankton recorder",
            "Idronaut sensors",
            "Imaging Plate for Gas Bubbles",
            "IMBC lander",
            "In situ benthic flux chamber",
            "In situ cell tracker",
            "In situ Chemical Sensor System",
            "In situ filtration sampler",
            "In situ gas tight sampler",
            "In situ incubation chamber ",
            "In situ Instrument",
            "In situ interstitial water sampler",
            "In situ oxygen microprofiler",
            "In situ pump",
            "In situ pump/Acoustic Doppler current profiler mooring",
            "In situ rhizone sampler",
            "In situ sampler",
            "In situ Schlieren-optic",
            "In-situ Camera Profiler",
            "Inclinometer",
            "Increment bohrer/beam disc",
            "Incubation",
            "Incubation, in situ productivity",
            "Indian Ocean Standard Net",
            "Industrial corer",
            "INSINC Corer (MPI)",
            "Instorf corer",
            "Instorf drill",
            "Instorf sampler",
            "Integrated System for Environmental Monitoring (SIMA)",
            "Interface Corer",
            "Interface water sampler",
            "Inverted echo sounder equipped with pressure sensor",
            "Iridium drifter",
            "Iron fish",
            "Iron-Manganese Sensor",
            "Isaac-Kid-Midwater Trawl",
            "ISIS MS2000",
            "ISTUK electromechanical drill",
            "ITU Corer",
            "Jellyfish net",
            "Jigging machine",
            "Jowsey corer",
            "Juday net",
            "Jumbo Piston Core",
            "Kajak sediment core sampler",
            "Kammerlander mooring",
            "Kasten corer",
            "Kasten corer (1 m**2)",
            "Kasten corer 15 cm",
            "Kasten corer 20 cm",
            "Kasten corer 30 cm",
            "Kasten corer RUS",
            "KIPS bottle",
            "Kiruna Microwave Radiometer",
            "Knife",
            "KONGSBERG EM122",
            "Krill net",
            "KULLENBERG corer",
            "Large Aggregate Profiling System",
            "Large collection box",
            "Large horizontal hauling net",
            "Large hydraulic grab",
            "Large lift Colossos",
            "Large volume water sampler",
            "Larvae net",
            "Laser distance meter, 3100HS, Riegl",
            "Laser distance meter, PS100EL, IBEO",
            "Laser optical particle counter",
            "Laser Optical Plankton Counter with CTD",
            "Laserscatterometer",
            "Lasertransmissometer",
            "Let Go",
            "Letteval sampler",
            "LI-1800 UW (LI-COR Instruments)",
            "LiDAR, terrestrial",
            "Light meter",
            "Light sonde",
            "Light Weight Piston Corer",
            "Lightframe onsight keyspecies investigation",
            "LIMNOS water sampler",
            "Line Fishing Bait",
            "Line Hook Bait",
            "LIR-Meter",
            "Literary studies",
            "Livingstone borer",
            "Livingstone corer",
            "Livingstone piston corer",
            "Livingstone piston sampler",
            "Location-only transmitter",
            "Long gravitational tube",
            "Long Line; Demersal; hook=EZ(11/0); bait=Squid",
            "Long Ranger",
            "Long-term vent sampler",
            "Longline deployment",
            "Lovrich dredge",
            "Lowerd Acoustic Doppler Current Profiler",
            "Lowered Acoustic Doppler Current Profiler",
            "LUISE Lander",
            "Lysimeter",
            "M-ODP",
            "Mackereth corer",
            "Mackereth sampler",
            "Magnetic profile",
            "Magnetic Turn Circle",
            "Magnetometer",
            "Magnetotelluric",
            "Manipulator arm",
            "manned balloon",
            "Manually-driven titanium corer, Model BTC, Duncan",
            "Marine endotherm",
            "Marine environmental meas syst",
            "Marine snow catcher",
            "Mark III motorized coring device, Kovacs Enterprise Inc",
            "Mark VI motorized coring device, Kovacs Enterprise Inc",
            "Marker",
            "MARVOR float",
            "MASCOT",
            "Mass spectrometer, in situ",
            "MaxiCorer",
            "McLane Moored Profiler",
            "McLane Pump",
            "MeBo (Meeresboden-Bohrgerät)",
            "MeBo200",
            "MeBo70",
            "MegaCorer",
            "Membrane pump",
            "Mercos water sampler",
            "Merkt corer",
            "Mesocosm experiment",
            "Meßhai",
            "Metal boxes",
            "Metal boxes (30x5 cm)",
            "Metal boxes (40x10x10 cm)",
            "Metal boxes (50x8x8 cm)",
            "Metal boxes (8x8 cm)",
            "Meteorological buoy",
            "Methane survey",
            "Micro net",
            "Micro plankton net",
            "Micro structure probe",
            "Micro structure turbulence",
            "Microsensor profiler",
            "Microsensor-ex situ",
            "Microstructure Profiler",
            "Mid-Ieapetra Deep mooring",
            "MidiCorer",
            "Midwater Ring Net",
            "Midwater trawl",
            "Midwater trawl, Engels 800",
            "Mini Box Corer",
            "Miniature Autonomous Plume Recorder",
            "Miniature Temperature Logger",
            "Miniaturized temperature logger",
            "MiniCorer",
            "MIR deep-sea manned submersible",
            "MIR-1 deep-sea manned submersible",
            "MIR-2 deep-sea manned submersible",
            "MOCNESS opening/closing plankton net",
            "MOCNESS opening/closing plankton net 1 sqm",
            "MOCNESS opening/closing plankton net 10 sqm",
            "Model",
            "Modem",
            "Modular Acoustic Velocity Sensor",
            "Mondsee corer",
            "Monegasque Trawl",
            "Monitoring",
            "Monitoring station",
            "Monolith boxes",
            "Monolith boxes (10x10 cm)",
            "Monolith boxes (10x10x75 cm)",
            "Monolith tins (1x3x3 cm)",
            "Monolith tins (1x3x30 cm)",
            "Moored onsight keyspecies investigation",
            "Mooring",
            "Mooring (long time)",
            "Mooring (short time)",
            "Moos Net",
            "Moving Lander",
            "Moving Vessel Profiler",
            "MPI-Megacam",
            "MS2000",
            "Multi autoclave corer",
            "Multi Brine Sampler",
            "Multi corer, Octopus",
            "Multi fibre optics sensor mooring",
            "Multi frame",
            "Multi Mini-Corer",
            "Multi Plankton Sampler XL",
            "Multi pump",
            "Multi Sensor Device",
            "Multibeam",
            "Multibeam/Parasound",
            "Multiboxcorer",
            "Multichannel seismics",
            "MultiCorer",
            "MultiCorer Barnett pattern (12-57)",
            "MultiCorer Barnett pattern (4-57.8-74)",
            "MultiCorer Barnett pattern (8-92)",
            "Multicorer with television",
            "MultiCorer, mini",
            "MultiCorer, small",
            "Multiple investigations",
            "Multiple opening/closing net",
            "Multiple opening/closing net, 100 µm meshsize",
            "Multiple opening/closing net, 150 µm meshsize",
            "Multiple opening/closing net, 200 µm meshsize",
            "Multiple opening/closing net, 300 µm meshsize",
            "Multiple opening/closing net, 500 µm meshsize",
            "Multiple opening/closing net, 55 µm meshsize",
            "Multiple opening/closing net, 64 µm meshsize",
            "Multiple revolver box corer",
            "Multiple Unit Large Volume Filtration System",
            "Multiprobe ECO-159",
            "Multipurpose pelagic trawl - 832",
            "Multisensor device",
            "Multisonde",
            "N-ODP",
            "Nansen closing net",
            "Nautile",
            "Navigationslot bottom survey",
            "Nemo float",
            "Nephelometer",
            "Net",
            "Net 100 µm",
            "Net 50 µm",
            "Net 600 µm 10 x 1 m**2",
            "net barrier (1mm mesh size)",
            "Neuston net",
            "Neuston sledge",
            "New trap technology array",
            "Niederreiter Piston corer",
            "Niemistoe corer",
            "NIMROD",
            "NIOZ square box corer",
            "Nipri net",
            "No_Oxygen_Exchange bottle 7L",
            "NOAA-Drifter",
            "not_given",
            "Nv-Shuttle",
            "Observation",
            "Ocean 70 grab",
            "Ocean bottom electro-magnetic receiver",
            "Ocean Bottom EM / MT",
            "Ocean bottom hydrophone",
            "Ocean Bottom Pressure Meter",
            "Ocean bottom seismometer",
            "Ocean Bottom Tiltmeter",
            "Ocean Floor Observation System",
            "Ocean tracer Injection System",
            "Ocean-50 grab",
            "Oceangraphic instrument Mabel",
            "Oceanlab Spreader-Mesocosm",
            "Oceanographic recorder tow",
            "Oceanography",
            "Okean Grab",
            "Omori net",
            "Open ocean station",
            "Optical backscatter",
            "Optical cast",
            "Optical Profiler, HyperPro",
            "Optical Profiler, Scripps Institution",
            "Optical refractometer",
            "Optical sensor",
            "Optics CTD",
            "Orpheus lander system",
            "Otter trawl",
            "Outcrop sample",
            "Oxygen optode",
            "Oxygen profiler",
            "Ozone sonde",
            "Paleontological sampling",
            "ParaSound",
            "Parasound, frequency test",
            "Particle camera",
            "Particle Camera System with CTD",
            "Passelaigue net",
            "Passive Acustic Monitoring System",
            "Peat corer",
            "Peat drill",
            "Peeper",
            "PEGASUS",
            "PEGAZ",
            "Pelagial net",
            "Pelagic fish trawl",
            "Pelagios",
            "Penetrometer",
            "Penfeld-CPTU",
            "Penfeld-Vp",
            "PEP bottle",
            "Percussion corer",
            "Permanent Pressure Gauge",
            "Peterson grab",
            "pH probe",
            "Phleger core",
            "Photo grab",
            "Photo sledge",
            "Photo sledge BGR",
            "Photo trawl",
            "Photo/Video",
            "Photon Counter",
            "Physics",
            "Phytoplankton net",
            "Phytoplankton net, Apstein-type",
            "Piezometer",
            "Pilcon wayfarer drilling rig",
            "PISCES deep-sea manned submersible",
            "Piston corer",
            "Piston corer (BGR type)",
            "Piston corer (Kiel type)",
            "Piston corer (UTIEC)",
            "Piston corer B (ODP)",
            "Pyranometer Network",
            "Piston corer Meischner large",
            "Piston corer Meischner small",
            "Piston corer Potsdam",
            "Piston corer Streif/Merkt",
            "Piston corer, hydro-pressure thin-walled",
            "Piston corer, UWITEC",
            "Piston push corer",
            "Piston sampler",
            "Piston-type corer, 75 cm",
            "Pitfall trap",
            "Planar optode",
            "Plankton net",
            "Plankton net BR 113/140",
            "Plankton net, conical",
            "Plankton pump",
            "Plankton recorder, continous",
            "Plankton recorder, Longhurst-Hardy",
            "Plankton recorder, video",
            "Plankton torpedo",
            "Plankton water sample",
            "Plastic pipe",
            "Plastic tube",
            "Pneumatic rotary drill \"SIF-650M\"",
            "Pneumatic-vacuum tube",
            "Poole sprat trawl",
            "Pore Water Pressure Lance, Lander",
            "Portuguese High-Headline Trawl",
            "Posidonia positioning system",
            "Pressure based acoustically coupled Tsunameter",
            "Pressure core barrel",
            "Pressure Piston Corer",
            "Pressure recorder",
            "pressure sensor",
            "Pressure water sampler",
            "Profile sampling",
            "Profiler",
            "Profiler, Max-Plank-Institute",
            "Profiling auto. lagrangian circulation explorer",
            "Profiling floater",
            "Profiling spectro-radiometer",
            "PROFILUR Lander",
            "PROVOR Float",
            "PumpCTD/Rosette",
            "Punch core",
            "Purse seine",
            "Push corer",
            "Push corer 10x10 cm",
            "Push-tube, UWITEC",
            "PVC bottle",
            "PVC tube",
            "Quadrapod corer",
            "Quantameter",
            "Quantameter/fluorometer, drifter",
            "Quantum Irradiance Meter (LICOR)",
            "Quarry",
            "Radar Doppler Current Profiler",
            "Radar profile",
            "Radiation-meter",
            "Radiometer",
            "Radiosonde",
            "RAFOS float",
            "Rain water collector",
            "Rammkernsonde",
            "Rammkernsonde/liner",
            "Rammlot",
            "RAMSES hyperspectral radiometer",
            "RBR Sensors",
            "Reconstructed data",
            "Recording Doppler Current Profiler 600",
            "Rectangular midwater trawl",
            "Rectangular midwater trawl 320 µm",
            "Rectangular midwater trawl 4500 µm",
            "Refraction buoy",
            "Release",
            "Remote operated platform for oceanography",
            "Remote operated vehicle",
            "Remote operated vehicle CHEROKEE",
            "Remote operated vehicle elevator",
            "Remote operated vehicle GENESIS",
            "Remote operated vehicle Jason II",
            "Remote operated vehicle MEDUSA",
            "Remote operated vehicle MOHAWK",
            "Remote operated vehicle QUEST",
            "Remote operated vehicle Sperre SubFighter 7500 DC",
            "Remote operated vehicle SPRINT 103",
            "Remote operated vehicle V8 Sii",
            "Remote operated vehicle VICTOR",
            "Remote sensing (Corona)",
            "Remote sensing (Landsat)",
            "Remote sensing (Light detection and ranging, LiDAR)",
            "Reprocessing plant",
            "Research station",
            "Research vessel",
            "Respirometer",
            "Reuse",
            "Reusenkette",
            "Ring net",
            "Ring trawl",
            "Ring trawl 1000 (h)",
            "Ring trawl 1000 (v)",
            "River gauging station",
            "Robotic arm",
            "Robust Biodiversity Lander",
            "Rock corer",
            "Rock drill",
            "Rock Drill 2",
            "Rock drill core",
            "Rock sample",
            "Rotary core drilling",
            "Rotary sampler",
            "Rotating corer",
            "Rotor/acoustic current meter",
            "ROV drawer",
            "ROV Swath bathymetry",
            "RoxAnn",
            "Rubber boat, Zodiac",
            "Rumohr-Lot",
            "Russian corer",
            "Russian peat borer",
            "Russian peat corer",
            "Russian peat sampler",
            "Russian sampler",
            "Russischer Kammerbohrer",
            "S-Probe",
            "Sampling by diver",
            "Sampling by hand",
            "Sampling gear, diverse",
            "Sampling lake",
            "Sampling permafrost",
            "Sampling river",
            "Sampling Well",
            "Sampling/measurement on land",
            "Sampling/measurements on glacier",
            "Satellite linked dive recorder",
            "Satellite linked dive recorder/CTD",
            "Satellite remote sensing",
            "Satlantic light sensor package",
            "SATPROFIL",
            "Scan fish",
            "Scoop/Biobox",
            "Scraper trawl",
            "Sea ice buoy",
            "Sea ice corer",
            "Sea soar profile",
            "Sea soar tow",
            "SeaBat 7150 multibeam echo sounder",
            "Seabeam survey",
            "Seabed High Resolution Imaging Platform",
            "Seafloor Sample",
            "SeaGuard RCM SW 4430",
            "SeaWiFS Multichannel Surface Reference",
            "SeaWiFS Profiling Multichannel Radiometer",
            "Secchi disc",
            "Secchi disc 30",
            "Sediment grabber, HYDRO-BIOS",
            "Sediment profile imagery",
            "Sediment sample",
            "Sediment tray free vehicle",
            "Sediment-Lot",
            "Seine net",
            "Seismic",
            "Seismic measurement station",
            "Seismic reflection profile",
            "Seismic refraction profile",
            "Seismic, shallow profile",
            "SEL core",
            "Semi-balloon trawl",
            "Sensor hand held",
            "Separator",
            "Sequential multicorer",
            "Sequential multiple corer",
            "Seston GF/F filter",
            "Settling velocity tube",
            "Shallow drilling",
            "Shallow sediment traps",
            "Ship Weather Station",
            "Ships non-toxic pump",
            "Sholkovitz gravity corer",
            "Shore seine",
            "Short temperature lance",
            "Shovel",
            "Side Scan Sonar",
            "Sigsbeesche Lotspindel + Bachmannsche Schlammröhre",
            "Sigsby trawl",
            "Simrad ER60 echo sounder (18, 38, 70, 120, 200 kHz)",
            "Simrad Multibeam",
            "Singel MOCNESS 2000",
            "SIPRE Auger",
            "SIPRE corer",
            "SIPRE corer and Ti chisels",
            "Sliced with band saw",
            "Slurp Gun",
            "SMAC",
            "Small collection box",
            "Small horizontal hauling net",
            "Smith corer",
            "SML Mini-Lander",
            "Snatch",
            "Snorkel with pump",
            "Snow pit",
            "Snow trench",
            "Snow/ice sample",
            "SOFAR float",
            "Soil pit",
            "Soil profile",
            "Sonar boje",
            "Sound Source",
            "Sound velocity probe",
            "Sound velocity profiler",
            "Soundprobe",
            "Soutar corer",
            "Spade",
            "Spade box corer",
            "Spade coring technique",
            "Sparker",
            "Spectral radiometer",
            "Spectrophotometer",
            "Speleothem sample",
            "Sphincter corer",
            "Spreaders",
            "Sputnik Electromagnetic Dipole Transmitter",
            "Square Corer (Marion Dufresne)",
            "Square-rod piston corer",
            "Stainless steel bottle 500L",
            "Stake",
            "Stand-alone pump on free-fall rig",
            "Stand-alone pumps",
            "Standard net",
            "Station",
            "Steel tube",
            "Stoss/Stechkasten",
            "Stow net University Bremen, width 3 m, height 4 m, meshsize 1 cm",
            "Streif corer",
            "Subbottom profiler",
            "Subfossil tree",
            "Submersible",
            "Submersible Alvin",
            "Submersible CYANA",
            "Submersible Deepstar-4000",
            "Submersible JAGO",
            "Submersible Johnson Sea Link",
            "Submersible mounted corer",
            "Submersible NAUTILE",
            "Submersible PISCES",
            "Submersible Shinkai 2000",
            "Suction sampler",
            "Surface and under ice trawl",
            "Surface Buoy Unit",
            "Surface methane survey",
            "Surface UNderway carbon Dioxide partial pressure ANalySer",
            "Surface water monitoring system",
            "Surface water sample",
            "Survey",
            "Swath bathymetry mapping",
            "Symbiosis catcher",
            "T-80 net, 375 µm mesch size",
            "T-Stick",
            "Tap",
            "Tauchersondierung",
            "TDR-Minilog",
            "Teflon coated stainless steel core barrel",
            "Television microsensor profiler",
            "Television Multi-Autoklave corer",
            "Television sled",
            "Television-Grab",
            "Temperature Lance",
            "Temperature Probe",
            "Temperature recorder",
            "Test",
            "Tether Management system",
            "Tethered camera survey",
            "Tetra net",
            "Thermal drill",
            "Thermal drill, dry hole",
            "Thermal imaging system",
            "Thermistor chain",
            "Thermistor chain 100 m",
            "Thermistor chain 300 m",
            "Thermistor chain 50 m",
            "Thermistor Gravity Corer",
            "Thermistor recorder",
            "Thermosalinograph",
            "Ti coated handsaw",
            "Tide gauge station",
            "Tile bags",
            "Time domain reflectometry",
            "Titan Bottle",
            "TM corer and Ti chisels, Lichtert Industrie",
            "Tow net",
            "Towed Acoustic Doppler Current Profiler",
            "Towed Ocean Bottom Instrument",
            "Towed zooplankton net",
            "Towed, trawled camera sled",
            "TRAC",
            "Tracor Acoustic Profiling System",
            "Transfer of samples/instruments from/to seafloor",
            "Transparent bottle 150L",
            "Transparent bottle 50L",
            "Transparent Plastic Nansen water sampler",
            "Transponder",
            "Trap",
            "Trap, amphipod",
            "Trap, baited",
            "Trap, drifting",
            "Trap, fish",
            "Trap, micrometeorite",
            "Trap, particle interceptor",
            "Trap, pollen",
            "Trap, sediment",
            "Trap, sediment, drifting",
            "Trap, sediment, floating",
            "Trap, shorttime",
            "Trawl net",
            "Trawl-resistant, bottom-mounted Acoustic Doppler Current Profiler",
            "Tree drill",
            "Tree ring sampling",
            "Tree ring sampling of historical object",
            "Triangle frame",
            "Triax system",
            "TRIAXUS",
            "Trigger corer",
            "TriOS light sensor package",
            "Tripod gravity corer",
            "Trolling fishing",
            "Truck mounted rotary drill",
            "Tube worm",
            "Tubewell",
            "Tuck seine net",
            "Tucker trawl, one opening/closing net",
            "Turbulence measurements",
            "Turbulence probe",
            "Ultra violet radiation measurement",
            "Underwater quantum sensor",
            "Underwater spectrometer",
            "Underwater video profiler",
            "Underwater Video system",
            "Underway air sampling",
            "Underway atmosphere observatory",
            "Underway cruise track measurements",
            "Underway pCO2 measurements",
            "Underway water sampling",
            "Undulator",
            "Unmanned aerial vehicle",
            "Unmanned gauge station",
            "Unmanned weather station/meteorological observation",
            "USC Lander",
            "Usinger corer",
            "Usinger Piston Corer",
            "USNEL Box Corer",
            "van Veen Grab",
            "van Veen Grab, mini",
            "Variable length HPC (DSDP)",
            "Vent sampler",
            "Versatile INstrument for the Determination of Total inorganic carbon and titrati",
            "Vertical amphipod trap",
            "Vertical net",
            "Vertical plankton net",
            "Vessel mounted Acoustic Doppler Current Profiler 150 kHz",
            "Vessel mounted Acoustic Doppler Current Profiler 38 kHz",
            "Vessel mounted Acoustic Doppler Current Profiler 75 kHz",
            "Vibration corer IOW",
            "Vibro Corer",
            "Vibrohammer GSF",
            "Victor6000 ROV",
            "Video camera",
            "Video-CTD",
            "Visual identification",
            "Voreillot_BGR",
            "Wadenaar Corer",
            "Wardenaar corer",
            "washed (DSDP/ODP)",
            "Water gage",
            "Water level recorder",
            "Water Multi Sampler",
            "Water pressure sensor",
            "Water pump",
            "Water sample",
            "Water sample, rain",
            "Water sampler, UWITEC",
            "WaxCorer",
            "Way point",
            "Weather station/meteorological observation",
            "Whale watching",
            "Whinch",
            "Whinch, underwater",
            "Whole core squeezer",
            "Wide-angle survey photography vehicle",
            "Wieckowski piston corer",
            "Wieckowski sampler",
            "Wired profile sonde",
            "Wollenburg corer",
            "Wood substrat",
            "WP-2 towed closing plankton net",
            "WP-3 towed closing plankton net",
            "XBT, aircraft deployed",
            "Young fish trawl",
            "Yoyo-CTD",
            "Z-ODP",
            "Zero-angle photon spectrometer",
            "Zooplankton net",
            "Zooplankton profiler",
            "Zremb BC 9VS corer"
    };

    public static final String[] deviceShortNames = {

            "2mBT",
            "3DCAM",
            "8-CTL",
            "AC-9",
            "AGSS",
            "DRG_A",
            "ADCP",
            "VMADCP",
            "ACM",
            "ARL",
            "ASMS",
            "AHPC",
            "ASIR",
            "AEOLD",
            "AERP",
            "AIRFILT",
            "AIRPUMP",
            "AERO",
            "AEROS",
            "AGT",
            "AGP",
            "SPUSO",
            "EMA",
            "ARES",
            "AC",
            "APEX",
            "NIOZL",
            "AF",
            "CPUMP",
            "ROV_AB",
            "APAC",
            "AFLOAT",
            "APNET",
            "AQM",
            "AQT",
            "ARGOFL",
            "ARGOS",
            "ARGOS_SI",
            "ARB",
            "AUG",
            "ARIES",
            "ACROV",
            "APC",
            "ADG",
            "ASSS",
            "AWS",
            "MACOL",
            "MAP",
            "ALACE",
            "ASSMO",
            "AUV",
            "AUV_MB",
            "AXE",
            "DEMAR",
            "BBS",
            "BBLM",
            "BHOOK",
            "BARO",
            "BSNACK",
            "BSNAP",
            "BS",
            "Batomat",
            "BK",
            "BSE",
            "BEAM",
            "BKKu3.5m#01cmRO",
            "BKKu8.0m#01cmRO",
            "BKSe2.0m#01cmGK",
            "BKSe4.0m#01cmGK",
            "BKSe4.0m#04cmGK",
            "BKSe2.0m#0.4cm",
            "BKSe2.0m#01cmG-",
            "BKSe4.0m#01cmG-",
            "BKPo7.5m#01cmRO",
            "BKPR3.0m#01cmRO",
            "BKPR3.0m#01cmGK",
            "BKPR3.0m#01cmG-",
            "CHAM",
            "BCL",
            "BCRAWL",
            "BECI",
            "BFC",
            "SD-BFC",
            "BFM",
            "BME",
            "BOLAS",
            "BBL",
            "BPT",
            "BETON",
            "BSL",
            "BIBO",
            "BICS",
            "BOP",
            "BRO",
            "BIOMAP",
            "BRIL",
            "BIGO",
            "BIOS",
            "BIO",
            "BIOMAPER",
            "BIOMOC",
            "BCROV",
            "BOBBER",
            "BOB",
            "BONGO",
            "BOO",
            "BG",
            "BL",
            "BOR",
            "BM",
            "BS500",
            "KEM",
            "MLTM",
            "NB",
            "NB_10L",
            "NB_4L",
            "NB_5L",
            "NAS",
            "NIS",
            "NIS_1.6L",
            "NIS_10L",
            "NIS_12L",
            "NIS_2L",
            "NIS_20L",
            "NIS_25L",
            "NIS_3L",
            "NIS_30L",
            "NIS_5L",
            "NIS_8L",
            "RWS",
            "BOT",
            "BOT_10L",
            "BOT_2L",
            "BOT_20L",
            "BOT_4L",
            "BOT_5L",
            "VDB",
            "VDB_2.2L",
            "B-ADCP",
            "BOBO",
            "BP",
            "SMG",
            "B_LANDER",
            "BL_C",
            "BL_L",
            "BL_P",
            "BN",
            "BPR",
            "BT",
            "BWS",
            "BWST",
            "BWTM",
            "B_CSEM",
            "BC",
            "rBX",
            "BCR002",
            "BCR",
            "BCP",
            "BOX5520",
            "BB-OBS",
            "BUC",
            "BUCL",
            "BUCS",
            "BUM",
            "BMB",
            "BUCKET",
            "WB",
            "BB",
            "BMA",
            "BSRN",
            "BUOY",
            "BF",
            "BYP",
            "BYES",
            "CA",
            "CALCOFI",
            "INT",
            "CAL",
            "CALMAR",
            "CASCC",
            "CALYPSO",
            "CALYPSO2",
            "CALYPSO3",
            "CASQS",
            "CASQ",
            "CAME",
            "CS",
            "HOP",
            "CAMP",
            "CMP",
            "CARB",
            "CAT",
            "CATM",
            "MESSIN",
            "CENSUS",
            "CENT",
            "CSAW",
            "CP",
            "CC",
            "CHEM",
            "CHP",
            "CHRIS",
            "DRG_Cl",
            "CLAW",
            "CPIT",
            "CMS",
            "SN",
            "ST",
            "CO2S",
            "CSEC",
            "CPC",
            "COLBOX",
            "CFG",
            "COLT",
            "CGU",
            "COL-MACRO",
            "COL-MICRO",
            "COMPCORE",
            "CPT",
            "GOST",
            "GPCENT",
            "CSEM",
            "CO",
            "CORE",
            "CDRILL",
            "CWS",
            "CSUB",
            "CTN",
            "COUC",
            "CRAEC",
            "CTDIF",
            "CTD-L",
            "CTD-GC",
            "CTD-ADCP",
            "CTD-F",
            "CTD-RCST",
            "CTD-SF",
            "ICTD",
            "hCTD",
            "CTD-M",
            "TRAMP",
            "CTD-R",
            "CTD-S",
            "CTD-UW",
            "CTD-RO",
            "CTD-UC",
            "CM",
            "CMM",
            "CMA",
            "VMCM",
            "VACM",
            "XCP",
            "DACH",
            "Tripod",
            "DC",
            "SEAMON",
            "DGRAB",
            "DFROV",
            "DLDS",
            "DOBS",
            "DOP",
            "DOSOL",
            "DOS",
            "DT",
            "DASI",
            "DTS",
            "DWS",
            "D-LIFT",
            "EM120",
            "FTRW-D",
            "DD",
            "DDRILL",
            "DIAL",
            "DPP",
            "DRG_D",
            "DIGER",
            "DPIT",
            "DI",
            "DN",
            "DHC",
            "DE",
            "DOMEST",
            "FMCWDR",
            "DO",
            "MOC-D-333",
            "D-MOC",
            "DMOC",
            "DWCP",
            "DRG",
            "BD",
            "DRG_B",
            "DRG_BU",
            "DRG_C",
            "DRG_F",
            "DRG_IGL",
            "DRG_P",
            "RD",
            "DRG_R",
            "TAD",
            "DRIFT-NET",
            "DRC",
            "DRIFT",
            "TD",
            "LD",
            "DRILLHY",
            "DRILL",
            "SEDFLO",
            "DS",
            "DUMMY",
            "DUC",
            "DPC",
            "DAPC",
            "ECHO",
            "3.5kHz",
            "ECO191",
            "TEMPO",
            "ECS",
            "EC",
            "EDDY",
            "EDEA",
            "EDEC",
            "ET",
            "EKB",
            "EG",
            "ELAC",
            "EMB",
            "EML",
            "EMD",
            "EMD-D",
            "EMD-F",
            "ESSC",
            "ELINOR",
            "NER-II",
            "EM1002",
            "EM302",
            "EM710",
            "ENV",
            "EBS",
            "EDRILL",
            "EQL",
            "EQL_pc",
            "EQL_tf",
            "EXC",
            "XBT",
            "XCTD",
            "XSV",
            "EXP",
            "EPC",
            "Exp_Tank_1m3",
            "Exp_Tank_4m3",
            "EXPLOS",
            "EXPO",
            "XCB",
            "EXT",
            "FAL",
            "FT-PP",
            "FX",
            "FBOX",
            "FERT",
            "FIRN",
            "FB",
            "FCROV",
            "FLS",
            "EK60",
            "FISH",
            "FLN",
            "FPOLE",
            "FR",
            "FIAS",
            "FLUEGEL",
            "FLUFOL",
            "FLUFO",
            "FLUORS",
            "FLU",
            "FRRF",
            "FLP",
            "FPUMP",
            "FP",
            "FC",
            "FRA",
            "FFC",
            "FFGR",
            "FPS",
            "FFP-CTD",
            "FVGR",
            "FFI",
            "FFR",
            "FFRK",
            "FFWS",
            "FFB",
            "FRC",
            "FT",
            "FTIR-WST",
            "FUPO",
            "GBS",
            "GSC",
            "GHE",
            "GASQUANT",
            "ROV_GS",
            "GSPT",
            "GTSB-ROV",
            "GQ",
            "GSAMP",
            "GS",
            "GNC_X",
            "GNC",
            "GEM",
            "GDS",
            "GEOEL",
            "GGT",
            "GEOMAP",
            "GEOPRO",
            "GEOS",
            "MAGOBS",
            "GEOMAG",
            "GEOC",
            "GEOP",
            "GTC",
            "GEOT",
            "GB",
            "GES10",
            "GKG",
            "GBG",
            "GGC",
            "GSL",
            "GPC",
            "GPC-C",
            "GWS",
            "GN",
            "GSWS",
            "GLD",
            "GAPS",
            "GNSS",
            "GOFLO10L",
            "GOFLO30L",
            "GOFLO",
            "GBGL",
            "GBMAXL",
            "GBMINIL",
            "GISMO",
            "GODESS",
            "GA_5",
            "GA",
            "GRAB",
            "SHIPEK",
            "GTVA",
            "GTVC",
            "GTVD",
            "GOV36-47",
            "GOVT",
            "GT",
            "GRAV",
            "GC",
            "SL",
            "GC_POI",
            "RGC",
            "SL_G",
            "GC_PP",
            "SL_P",
            "HSL",
            "GCUWI",
            "GHF",
            "GC_T",
            "GPR",
            "GPS",
            "GULF",
            "HADAL",
            "HAM",
            "HPS",
            "HADR",
            "HB",
            "HBS",
            "HCOR",
            "HCI",
            "HDRILL",
            "HID",
            "HN",
            "HPIC",
            "HP",
            "HSR",
            "TROW",
            "HWS",
            "HAPS",
            "HASA",
            "HF",
            "HFHG",
            "HMWS",
            "HELGLARV",
            "HELI",
            "HNET",
            "HFR",
            "HILB",
            "HILC",
            "HPA",
            "HILS",
            "HO",
            "HONK",
            "HORIZON",
            "HOBS",
            "HUNTN",
            "HDSD",
            "HyBIS",
            "HPC",
            "HYC",
            "HYOP",
            "HSUR",
            "HYD",
            "HMS",
            "HYDRO",
            "OLT-D",
            "HS",
            "HS_PS",
            "HYSP",
            "DRIFTERICBM",
            "ICEDRILL",
            "ICEM",
            "ICE",
            "ICESUR",
            "ICEB",
            "IPR",
            "IDRO",
            "IP",
            "IMBC",
            "ISBFC",
            "ISCT",
            "CHEMINI",
            "ISF",
            "ISGT",
            "ISCHAM",
            "ISI",
            "ISIWS",
            "IMP",
            "ISP",
            "ISP/ADCP",
            "RISS",
            "ISS",
            "ISSO",
            "ISC",
            "IN",
            "DENDRO",
            "INCUB",
            "ISPROD",
            "IOSN",
            "INDC",
            "INSINC",
            "INSC",
            "INSD",
            "INSS",
            "SIMA",
            "GCI",
            "IWS",
            "PIES",
            "ISD",
            "IFISH",
            "FeMn-S",
            "IKMT",
            "ISIS",
            "ISTUK",
            "ITUC",
            "JFN",
            "JIG",
            "JOWC",
            "JUDAY",
            "JPC",
            "KC",
            "KAMM",
            "KAL",
            "KASTEN",
            "KAL15",
            "KAL20",
            "KAL30",
            "KAL_R",
            "KIPS",
            "KIMRA",
            "KNIFE",
            "KEM122",
            "KN",
            "KULC",
            "LAPS",
            "GBT",
            "LHHN",
            "LHG",
            "COLOSSOS",
            "LVS",
            "LN",
            "3100HS",
            "PS100EL",
            "LOPC",
            "LOPC-CTD",
            "LSM",
            "LTM",
            "LETGO",
            "LETS",
            "LICOR",
            "LiDART",
            "LM",
            "LMS",
            "LWPC",
            "LOKI",
            "LIMNOSWS",
            "LFB",
            "LHB",
            "LIR",
            "LIT",
            "LIVB",
            "LIVC",
            "LPC",
            "LPS",
            "LOT",
            "LGT",
            "LLDEZS",
            "LR",
            "LOVESA",
            "LLDEP",
            "LOV-D",
            "LADCP-300",
            "LADCP",
            "LUISE",
            "LYSI",
            "M",
            "MACC",
            "MACS",
            "PRM",
            "MTC",
            "MAG",
            "MT",
            "ROV_MA",
            "MBALL",
            "BTC",
            "MET",
            "MUM",
            "MSC",
            "MARKIII",
            "MARKVI",
            "MRK",
            "MARVOR",
            "MASCOT",
            "BLC",
            "MAXC",
            "MMP",
            "McLP",
            "MeBo",
            "MeBo200",
            "MeBo70",
            "MEGAC",
            "MP",
            "MWS",
            "MCOR",
            "MESO",
            "MHAI",
            "MBOX",
            "MBOX305",
            "MBOXL",
            "MBOX5088",
            "MBOX88",
            "BUOY_MET",
            "METHAN",
            "MIN",
            "MPN",
            "MSS",
            "MST",
            "MICP",
            "MICS",
            "MSSP",
            "MID",
            "MDC",
            "MIK-N",
            "MWT",
            "MWT-E800",
            "MBC",
            "MAPR",
            "MTL",
            "MTL",
            "MIC",
            "MIR",
            "MIR-1",
            "MIR-2",
            "MOC",
            "MOC1",
            "MOC10",
            "Model",
            "MODEM",
            "MAVS",
            "MSCO",
            "MTRW",
            "MON",
            "MONS",
            "MONOB",
            "MONOBS",
            "MONOBL",
            "MTINS",
            "MTINL",
            "MOKI",
            "MOOR",
            "MOORY",
            "MOORST",
            "MO",
            "MOVE",
            "MVP",
            "MCAM",
            "MS2000",
            "MAC",
            "MBS",
            "MUC-OCT",
            "MUFO",
            "MF",
            "MMIC",
            "MPSXL",
            "MUP",
            "MSD",
            "MB",
            "MB_PS",
            "MG",
            "MCSEIS",
            "MUC",
            "MCB57",
            "MCB57-74",
            "MCB92",
            "TVMUC",
            "MCM",
            "MCS",
            "MULT",
            "MSN",
            "MSN100",
            "MSN150",
            "MSN200",
            "MSN300",
            "MSN500",
            "MSN55",
            "MSN64",
            "RKG",
            "MULVFS",
            "MPR",
            "MULTPELT-832",
            "MSDV",
            "MS",
            "N",
            "NN",
            "NAUT",
            "NAV",
            "NFLOAT",
            "NMR",
            "NET",
            "NET100",
            "NET50",
            "NET600",
            "NB1",
            "NEU",
            "NS",
            "NTTA",
            "NPC",
            "NC",
            "NIM",
            "sBX",
            "NIP",
            "NOEX_7L",
            "NOA-DRI",
            "n_g",
            "NVSHUTTLE",
            "OBSE",
            "O70",
            "OBEM",
            "OBMT",
            "OBH",
            "OBP",
            "OBS",
            "OBT",
            "OFOS",
            "OTIS",
            "GRAB50",
            "MABEL",
            "O_MESO",
            "UORT",
            "OCE",
            "OKEAN",
            "OM",
            "OOS",
            "OBSC",
            "OPT",
            "HPRO",
            "SIOP",
            "OPRA",
            "OS",
            "CTD-O",
            "ORPHEUS",
            "OT",
            "OUTCROP",
            "OPTODE",
            "O2PRO",
            "OZS",
            "PALSAMP",
            "PS",
            "PSFT",
            "PARCA",
            "PARCACTD",
            "PN",
            "PAM",
            "PEATC",
            "PD",
            "PEE",
            "PEGASUS",
            "PEGAZ",
            "PSN",
            "FTRW-P",
            "PGS",
            "PEN",
            "PenCPT",
            "PenVp",
            "PEP",
            "PCOR",
            "PPG",
            "PETG",
            "pH",
            "PCORE",
            "FBG",
            "FTS",
            "FS",
            "PT",
            "PV",
            "PHC",
            "PHYS",
            "PHYTONET",
            "PHY-NET",
            "PIEZO",
            "PWDRILL",
            "PISCES2",
            "PC",
            "KL",
            "KOL",
            "PCUT",
            "PCB",
            "PYRNET",
            "KL_Mg",
            "KL_Mk",
            "KOL_P",
            "PC_SM",
            "PC-hp",
            "PCUWI",
            "KS",
            "PSAMP",
            "PTC",
            "PTRAP",
            "PO",
            "PLA",
            "PN-BR",
            "PNC",
            "PP",
            "CPR",
            "LHPR",
            "VPR",
            "TOP",
            "PLAWS",
            "PPIP",
            "PTUB",
            "PRD",
            "PVTUB",
            "PST",
            "PWPL",
            "PHHT",
            "POS",
            "PACT",
            "B",
            "LDP",
            "PRES-R",
            "pswat",
            "PWS",
            "PROFILE",
            "PROF",
            "MPI-PRO",
            "PALACE",
            "PFLOAT",
            "MER",
            "PROFILUR",
            "PROVOR",
            "PCTD-RO",
            "H",
            "PSE",
            "PUC",
            "PUC10",
            "PTUWI",
            "PVCB",
            "PVCT",
            "QP",
            "QM",
            "QM_FL",
            "QIM",
            "QU",
            "RDCP",
            "RADAR",
            "PAR",
            "RM",
            "RADIO",
            "RAFOS",
            "RAIN",
            "RKS",
            "RKS_L",
            "RLot",
            "RAMSES",
            "RBRS",
            "RECON",
            "RDCP600",
            "RMT",
            "RMT1",
            "RMT8",
            "RFB",
            "REL",
            "ROPOS",
            "ROV",
            "ROVC",
            "ROV_E",
            "GENESIS",
            "ROVJ",
            "MEDUSA",
            "ROV-M",
            "ROVQ",
            "ROVSP",
            "ROVS",
            "ROVV8",
            "ROVV",
            "CSAT",
            "LSAT",
            "LiDAR",
            "RP",
            "RS",
            "RV",
            "RESP",
            "REUSE",
            "RK",
            "RN",
            "RTR",
            "RT-h",
            "RT-v",
            "RGS",
            "ROBA",
            "ROBIO",
            "ROCKC",
            "RDRILL",
            "RD2",
            "RDC",
            "ROCK",
            "RCD",
            "ROT",
            "RC",
            "RACM",
            "PAN",
            "ROV_SBM",
            "ROXA",
            "ZODIAK",
            "RL",
            "RUSC",
            "RPB",
            "RPC",
            "RPS",
            "RSAMP",
            "RKB",
            "SPB",
            "DIVER",
            "HAND",
            "DIVERSE",
            "LAKE",
            "PERM",
            "RIVER",
            "WELL",
            "LAND",
            "GLAC",
            "SDR",
            "SDRC",
            "SAT",
            "SLS",
            "SATP",
            "SCF",
            "SCOOP",
            "STRAWL",
            "BUOY_SI",
            "SEAICEC",
            "SEASOAR",
            "SST",
            "SB7150",
            "SEABEAM",
            "SHRIMP",
            "SFS",
            "SG 4430",
            "SMSR",
            "SPMR",
            "SD",
            "SD-30",
            "SGRABBER",
            "SEP",
            "SES",
            "STFV",
            "SES2000",
            "SNET",
            "SEIS",
            "SEISMS",
            "SEISREFL",
            "SEISREFR",
            "SEISS",
            "SEL",
            "OTSB14",
            "SHH",
            "SEPAR",
            "SMUC",
            "S-MUC",
            "GF/F",
            "SETVEL",
            "SHEL",
            "SSTR",
            "SWEAS",
            "GPUMP",
            "SHGRCORE",
            "SSE",
            "STL",
            "SHOVEL",
            "SS",
            "SLBS",
            "SIGSBY",
            "ER60",
            "SM",
            "MOC-S-2000",
            "SA",
            "SIPREC",
            "SIPRE",
            "BSAW",
            "SG",
            "SMAC",
            "PBT",
            "SHHN",
            "SMCOR",
            "SMLL",
            "SNATCH",
            "SNORKEL",
            "SNOWPIT",
            "SNOWTRE",
            "SNOW",
            "SOFAR",
            "SPIT",
            "SOIL",
            "SON",
            "SOSO",
            "SNDVELPR",
            "SVP",
            "SP",
            "SC",
            "SPADE",
            "VEGBOXC",
            "SCT",
            "SPA",
            "SPRA",
            "SPEC",
            "SPS",
            "SPC",
            "SPR",
            "SPUTNIK",
            "MDSC",
            "SRPC",
            "SSB500",
            "STAKE",
            "MSAPS",
            "SAPS",
            "STNET",
            "STAT",
            "STEELT",
            "SK",
            "PHUB",
            "STCOR",
            "SBB",
            "STREE",
            "SUB",
            "ALVIN",
            "CYANA",
            "DS4000",
            "JAGO",
            "JSL",
            "SMC",
            "NAUTILE",
            "PISCES",
            "S2000",
            "ASPI",
            "SUIT",
            "SBU",
            "SMS",
            "SUNDANS",
            "SWMS",
            "SWS",
            "SUR",
            "SBM",
            "SYMC",
            "T-80",
            "TST",
            "TAP",
            "TS",
            "TDR-M",
            "TCSS",
            "TV-MICP",
            "TV-MAC",
            "TV-S",
            "TVG",
            "TL",
            "TP",
            "TEMP-R",
            "TEST",
            "TMS",
            "CAM",
            "TN",
            "THERM",
            "THERM-D",
            "TIS",
            "THERMC",
            "TC-100",
            "TC-300",
            "TC-50",
            "TGC",
            "TR",
            "TSG",
            "TIHAND",
            "TGS",
            "TILEB",
            "TDR",
            "TiB",
            "TMC",
            "TOWN",
            "TADCP-300",
            "TOBI",
            "HAI",
            "TTCS",
            "TRAC",
            "TAPS",
            "SHUTTLE",
            "TRANS150",
            "TRANS50L",
            "TPN",
            "TRANSPO",
            "TRAP",
            "ATC",
            "TRAPB",
            "DF",
            "TRAPF",
            "TRAPMET",
            "PIT",
            "TRAPPOL",
            "TRAPS",
            "PELAGRA",
            "TRAPSF",
            "TRAPST",
            "TRAWL",
            "TRBM-ADCP",
            "TDRILL",
            "TREE",
            "TREES",
            "PCAM",
            "TRIAX",
            "TRIAXUS",
            "TC",
            "TRIOS",
            "TrGC",
            "TROLL",
            "RCDT",
            "TW",
            "TWELL",
            "TSEN",
            "TT",
            "TM",
            "TURPRO",
            "UVR",
            "UQS",
            "UWS",
            "UVP",
            "UWV",
            "UAS",
            "UWAOBS",
            "CT",
            "UWPCO2",
            "UWS",
            "UNDU",
            "UAV",
            "UGS",
            "UWST",
            "USCL",
            "UCOR",
            "UPC",
            "KGS",
            "VGRAB",
            "MVVG",
            "V",
            "VESP",
            "VINDTA-3C",
            "VET",
            "VNET",
            "VPN",
            "VMADCP-150",
            "VMADCP-38",
            "VMADCP-75",
            "VKG",
            "VC",
            "VC_G",
            "VICTOR",
            "VIDEO",
            "CTD-V",
            "VID",
            "VS",
            "WADC",
            "WCOR",
            "W",
            "WG",
            "WLR",
            "MUWS",
            "WPS",
            "PUMP",
            "WS",
            "WSR",
            "WSUWI",
            "WC",
            "WPT",
            "WST",
            "WHW",
            "WHINCH",
            "UWW",
            "WCS",
            "WASP",
            "WPC",
            "WSAMP",
            "WP",
            "WCROV",
            "WOOD",
            "WP2",
            "WP3",
            "AXBT",
            "YFT",
            "CTD-yoyo",
            "Z",
            "ZAPS",
            "ZNET",
            "ZPP",
            "ZREMB"
    };

    public DatabaseHelper(Context context){
        super(context, DB_NAME, null, DB_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db){
        //Create AIS Station List Table
        db.execSQL("CREATE TABLE "  + stationListTable + "(" + mmsi + " INTEGER PRIMARY KEY," +
                stationName + " TEXT NOT NULL );");

        //Create AIS Fixed Station Position Table
        db.execSQL("CREATE TABLE " + fixedStationTable + " (_id INTEGER PRIMARY KEY AUTOINCREMENT, " +
                stationName + " TEXT, " +
                latitude + " REAL, " +
                longitude + " REAL, " +
                recvdLatitude + " REAL, " +
                recvdLongitude + " REAL, " +
                alpha + " REAL, " +
                xPosition + " REAL, " +
                yPosition + " REAL, " +
                deviceType + " TEXT, " +
                updateTime + " TEXT, " +
                sog + " REAL, " +
                cog + " REAL, " +
                packetType + " INTEGER, " +
                isPredicted + " NUMERIC, " +
                predictionAccuracy + " NUMERIC, " +
                isLocationReceived + " NUMERIC, " +
                mmsi + " INTEGER NOT NULL, " +
                "FOREIGN KEY (" + mmsi + ") REFERENCES " + stationListTable + "(" + mmsi + "));");

        //Create Base Stations Table
        db.execSQL("CREATE TABLE " + baseStationTable + "(" + mmsi + " INTEGER PRIMARY KEY, " +
                stationName + " TEXT NOT NULL);");

        //Create Beta Table
        db.execSQL("CREATE TABLE " + betaTable + "(_id INTEGER PRIMARY KEY AUTOINCREMENT, " +
                beta + " REAL NOT NULL, " +
                updateTime + " TEXT);");

        //Create Users Table
        db.execSQL("CREATE TABLE " + usersTable + "(_id INTEGER PRIMARY KEY AUTOINCREMENT, " +
                userName + " TEXT NOT NULL, " +
                password + " TEXT);");

        insertUser(db, "awi", "awi");
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion){

    }

    public static boolean createTables(SQLiteDatabase db){
        //SQLiteDatabase db = this.getWritableDatabase();
        try{
            //Create Mobile Station Table
            db.execSQL("CREATE TABLE " + mobileStationTable + " (_id INTEGER PRIMARY KEY AUTOINCREMENT, " +
                    stationName + " TEXT, " +
                    latitude + " REAL, " +
                    longitude + " REAL, " +
                    alpha + " REAL, " +
                    xPosition + " REAL, " +
                    yPosition + " REAL, " +
                    deviceType + " TEXT, " +
                    updateTime + " TEXT, " +
                    mmsi + " INTEGER NOT NULL);");

            //Create Sample/Measurement Table
            db.execSQL("CREATE TABLE " + sampleMeasurementTable + " ( _id INTEGER PRIMARY KEY AUTOINCREMENT, " +
                    deviceName + " TEXT, " +
                    label + " TEXT);");

            //Create DeviceList Table
            db.execSQL("CREATE TABLE " + deviceListTable + " ( _id INTEGER PRIMARY KEY AUTOINCREMENT, " +
                    deviceName + " TEXT, " +
                    deviceShortName + " TEXT," +
                    deviceType + " TEXT," +
                    xPosition + " REAL, " +
                    yPosition + "REAL);");

            //Create StationList Table
            db.execSQL("CREATE TABLE " + staticStationListTable + " ( _id INTEGER PRIMARY KEY AUTOINCREMENT, " +
                    staticStationName + " TEXT, " +
                    stationType + " TEXT, " +
                    xPosition + " REAL, " +
                    yPosition + " REAL, " +
                    alpha + " REAL, " +
                    distance + " REAL);");

            //Create Waypoints Table
            db.execSQL("CREATE TABLE " + waypointsTable + " ( _id INTEGER PRIMARY KEY AUTOINCREMENT, " +
                    label + " TEXT); ");

            return  true;
        } catch(SQLiteException e){
            Log.d(TAG, "Database Unavailable");
            return  false;
        }

    }

    private void insertUser(SQLiteDatabase db, String name, String pass){
        ContentValues defaultUser = new ContentValues();
        defaultUser.put(userName, name);
        defaultUser.put(password, pass);
        db.insert(usersTable, null, defaultUser);
    }

    public String searchPassword(String uname){
        SQLiteDatabase db = this.getReadableDatabase();
        //String query = "SELECT USERNAME, PASSWORD FROM USERS";
        Cursor cursor = db.query(usersTable,
                new String[]{userName, password},
                null, null, null, null, null);
        String user, pwd;
        pwd = "Not Found";

        if (cursor.moveToFirst()){


            do {

                user = cursor.getString(0);
                if (user.equals(uname)){
                    pwd = cursor.getString(1);

                    break;
                }
            } while(cursor.moveToNext());
        }
        cursor.close();
        //db.close();

        return pwd;
    }

    public  double[] readBaseCoordinatePointsLatLon(){
        double[] coordinates = new double[4];
        try {
            SQLiteDatabase db = this.getReadableDatabase();

            Cursor cursor = db.query(fixedStationTable,
                    new String[]{latitude, longitude},
                    "(X_Position = ? AND Y_POSITION = ?) OR (X_POSITION = ? AND Y_POSITION = ? ",
                    new String[]{Long.toString(station1InitialX), Long.toString(station1InitialY), Long.toString(station2InitialX), Long.toString(station2InitialY)},
                    null, null, null);
            if (cursor.moveToFirst()) {
                int i = 0;
                do {

                    coordinates[i] = cursor.getDouble(cursor.getColumnIndex(latitude));
                    coordinates[i + 1] = cursor.getDouble(cursor.getColumnIndex(longitude));
                    i += 2;
                } while (cursor.moveToNext());
            }
            cursor.close();
            //db.close();
        } catch (SQLiteException e){
            Log.d(TAG, "Database Unavailable");
            e.printStackTrace();
        }
        return coordinates;
    }

    public static synchronized DatabaseHelper getDbInstance(Context context){
        if (dbInstance == null){
            dbInstance = new DatabaseHelper(context.getApplicationContext());
        }
        return dbInstance;
    }

    public static ArrayAdapter<String> advancedSearchTextView(Context mContext){

        ArrayAdapter<String> adapter = new ArrayAdapter<String>(mContext, android.R.layout.simple_dropdown_item_1line, deviceShortNames);
        return adapter;
    }

    public static String findDeviceFullName(String devShortName){

        int arrayIndex;
        for (arrayIndex = 0; arrayIndex < deviceShortNames.length; arrayIndex++){
            if (deviceShortNames[arrayIndex].equals(devShortName)){
                return deviceNames[arrayIndex];
            }
        }
        Log.d(TAG, "Device full name not found");
        return null;
    }

}
